version: '3'
services:
  edith:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8282:80"
      - "8082:8080"
      - "3690:3690"
    volumes:
      - data-volume:/opt/svn/
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "somepassword"

volumes:
  data-volume: