version: '3'
services:
  edith_jetty:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes: &edith_volumes
      - svn-volume:/opt/svn/
  web_svn:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8282:80"
    volumes: *edith_volumes
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "somepassword"
    volumes: 
      - data-volume:/var/lib/mysql

volumes:
  data-volume:
  svn-volume: