version: '3'
services:
  jetty:
    build:
      context: .
      dockerfile: Dockerfile.jetty
    ports:
      - "8082:8080"
    volumes: &edith_volumes
      - svn-volume:/opt/svn/
    restart: always
  
  web:
    build:
      context: .
      dockerfile: Dockerfile.apache
    depends_on: 
      - jetty
    ports:
      - "8282:80"
    volumes: *edith_volumes
    restart: always
  
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "somepassword"
    volumes: 
      - data-volume:/var/lib/mysql
    restart: always

volumes:
  data-volume:
  svn-volume: